### ISSUE TITLE
CommonJS require does not work as described in docs

### ISSUE THREAD

**Issue by Filipoliko** [tjmehta/error-to-json#6]
Hi,
according to the README, you can require the module as following.

```javascript
const errorToJSON = require('error-to-json');
```

But if you try to use `errorToJSON` as a function, you will receive an error `TypeError: errorToJSON is not a function`. This is because `errorToJSON` is actually exported under the `default` key and has to be required like this to work properly.

```javascript
const errorToJSON = require('error-to-json').default;
```

It would be great, to update docs, or the build process (which I'm not sure, if its possible).

**Comment by tjmehta** [comment]
Opps, I did not test this outside of TypeScript. Looks like you are right https://github.com/microsoft/TypeScript/issues/2719. I guess we should update the docs to include `.default`

**Comment by tjmehta** [comment]
update docs for now, if I get this fixed I will publish it as new major version (since it would be a breaking change). let me know how the error class works for you and if you have any other requests. thanks!
